In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/student_lifestyle_100k.csv')

In [3]:
df.head()

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False
3,1004,21,Male,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,1005,19,Male,Arts,3.14,6.8,2.6,4.3,4,6,False

In [4]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Department', 'CGPA', 'Sleep_Duration',
       'Study_Hours', 'Social_Media_Hours', 'Physical_Activity',
       'Stress_Level', 'Depression'],
      dtype='str')

In [7]:
new_cols = [col.lower() for col in df.columns]
df.columns = new_cols
df.columns

Index(['student_id', 'age', 'gender', 'department', 'cgpa', 'sleep_duration',
       'study_hours', 'social_media_hours', 'physical_activity',
       'stress_level', 'depression'],
      dtype='str')

In [10]:
# df.drop(columns=['student_id'], inplace=True)
df.head()

,age,gender,department,cgpa,sleep_duration,study_hours,social_media_hours,physical_activity,stress_level,depression
0,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False
3,21,Male,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,19,Male,Arts,3.14,6.8,2.6,4.3,4,6,False